### ISSUE TITLE
Clic en bas, à la limite de la fenetre

### ISSUE THREAD

**Issue by IAmFrench** [IAmFrench/Demineur#24]
- [ ] Ajouter forcer la vérification de la case avant de faire une op dessus

---

Code d'erreur générer :

`````` Python
    case=grille[caseclic]
KeyError: '6x10'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Alexandre\Anaconda3\lib\tkinter\__init__.py", line 1487, in __call__
    return self.func(*args)
  File "C:\Users\Alexandre\Documents\GitHub\Demineur\modgraph.py", line 231, in pointeurG
    clic0(xygrille)
  File "C:\Users\Alexandre\Documents\GitHub\Demineur\modclic.py", line 106, in clic0
    case=grille[caseclic]
KeyError: '6x10'```
``````

**Comment by IAmFrench** [comment]
![image](https://cloud.githubusercontent.com/assets/10818450/7898973/e3136888-0711-11e5-806d-e4c167f40d1a.png)
